TRUNCATE TABLE countries;
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('United States', 'US', 'US');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Afghanistan', 'AF', 'AF');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Albania', 'AL', 'AL');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Algeria', 'DZ', 'DZ');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Andorra', 'AD', 'AD');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Angola', 'AO', 'AO');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Antigua and Barbuda', 'AG', 'AG');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Argentina', 'AR', 'AR');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Armenia', 'AM', 'AM');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Australia', 'AU', 'AU');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Austria', 'AT', 'AT');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Azerbaijan', 'AZ', 'AZ');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Bahamas', 'BS', 'BS');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Bahrain', 'BH', 'BH');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Bangladesh', 'BD', 'BD');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Barbados', 'BB', 'BB');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Belarus', 'BY', 'BY');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Belgium', 'BE', 'BE');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Belize', 'BZ', 'BZ');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Benin', 'BJ', 'BJ');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Bhutan', 'BT', 'BT');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Bolivia', 'BO', 'BO');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Bosnia and Herzegovina', 'BA', 'BA');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Botswana', 'BW', 'BW');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Brazil', 'BR', 'BR');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Brunei', 'BN', 'BN');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Bulgaria', 'BG', 'BG');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Burkina Faso', 'BF', 'BF');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Burundi', 'BI', 'BI');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Cambodia', 'KH', 'KH');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Cameroon', 'CM', 'CM');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Canada', 'CA', 'CA');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Cape Verde', 'CV', 'CV');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Central African Republic', 'CF', 'CF');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Chad', 'TD', 'TD');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Chile', 'CL', 'CL');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES (E'People\'s Republic of China', 'CN', 'CN');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Colombia', 'CO', 'CO');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Comoros', 'KM', 'KM');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Congo - Kinshasa', 'CD', 'CD');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Congo - Brazzaville', 'CG', 'CG');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Costa Rica', 'CR', 'CR');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES (E'Cote d\'Ivoire (The Ivory Coast)', 'CI', 'CI');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Croatia', 'HR', 'HR');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Cuba', 'CU', 'CU');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Cyprus', 'CY', 'CY');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Czech Republic', 'CZ', 'CZ');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Denmark', 'DK', 'DK');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Djibouti', 'DJ', 'DJ');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Dominica', 'DM', 'DM');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Dominican Republic', 'DO', 'DO');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Ecuador', 'EC', 'EC');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Egypt', 'EG', 'EG');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('El Salvador', 'SV', 'SV');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Equatorial Guinea', 'GQ', 'GQ');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Eritrea', 'ER', 'ER');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Estonia', 'EE', 'EE');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Ethiopia', 'ET', 'ET');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Fiji', 'FJ', 'FJ');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Finland', 'FI', 'FI');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('France', 'FR', 'FR');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Gabon', 'GA', 'GA');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Gambia', 'GM', 'GM');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Georgia', 'GE', 'GE');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Germany', 'DE', 'DE');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Ghana', 'GH', 'GH');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Greece', 'GR', 'GR');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Grenada', 'GD', 'GD');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Guatemala', 'GT', 'GT');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Guinea', 'GN', 'GN');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Guinea-Bissau', 'GW', 'GW');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Guyana', 'GY', 'GY');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Haiti', 'HT', 'HT');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Honduras', 'HN', 'HN');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Hungary', 'HU', 'HU');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Iceland', 'IS', 'IS');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('India', 'IN', 'IN');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Indonesia', 'ID', 'ID');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Iran', 'IR', 'IR');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Iraq', 'IQ', 'IQ');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Ireland', 'IE', 'IE');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Israel', 'IL', 'IL');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Italy', 'IT', 'IT');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Jamaica', 'JM', 'JM');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Japan', 'JP', 'JP');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Jordan', 'JO', 'JO');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Kazakhstan', 'KZ', 'KZ');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Kenya', 'KE', 'KE');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Kiribati', 'KI', 'KI');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('North Korea', 'KP', 'KP');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('South Korea', 'KR', 'KR');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Kuwait', 'KW', 'KW');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Kyrgyzstan', 'KG', 'KG');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Laos', 'LA', 'LA');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Latvia', 'LV', 'LV');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Lebanon', 'LB', 'LB');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Lesotho', 'LS', 'LS');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Liberia', 'LR', 'LR');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Libya', 'LY', 'LY');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Liechtenstein', 'LI', 'LI');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Lithuania', 'LT', 'LT');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Luxembourg', 'LU', 'LU');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Macedonia', 'MK', 'MK');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Madagascar', 'MG', 'MG');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Malawi', 'MW', 'MW');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Malaysia', 'MY', 'MY');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Maldives', 'MV', 'MV');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Mali', 'ML', 'ML');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Malta', 'MT', 'MT');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Marshall Islands', 'MH', 'MH');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Mauritania', 'MR', 'MR');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Mauritius', 'MU', 'MU');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Mexico', 'MX', 'MX');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Micronesia', 'FM', 'FM');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Moldova', 'MD', 'MD');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Monaco', 'MC', 'MC');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Mongolia', 'MN', 'MN');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Montenegro', 'ME', 'ME');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Morocco', 'MA', 'MA');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Mozambique', 'MZ', 'MZ');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Myanmar (Burma)', 'MM', 'MM');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Namibia', 'NA', 'NA');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Nauru', 'NR', 'NR');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Nepal', 'NP', 'NP');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Netherlands', 'NL', 'NL');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('New Zealand', 'NZ', 'NZ');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Nicaragua', 'NI', 'NI');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Niger', 'NE', 'NE');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Nigeria', 'NG', 'NG');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Norway', 'NO', 'NO');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Oman', 'OM', 'OM');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Pakistan', 'PK', 'PK');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Palau', 'PW', 'PW');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Panama', 'PA', 'PA');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Papua New Guinea', 'PG', 'PG');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Paraguay', 'PY', 'PY');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Peru', 'PE', 'PE');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Philippines', 'PH', 'PH');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Poland', 'PL', 'PL');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Portugal', 'PT', 'PT');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Qatar', 'QA', 'QA');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Romania', 'RO', 'RO');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Russia', 'RU', 'RU');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Rwanda', 'RW', 'RW');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Saint Kitts and Nevis', 'KN', 'KN');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Saint Lucia', 'LC', 'LC');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Saint Vincent and the Grenadines', 'VC', 'VC');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Samoa', 'WS', 'WS');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('San Marino', 'SM', 'SM');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Sao Tome and Principe', 'ST', 'ST');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Saudi Arabia', 'SA', 'SA');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Senegal', 'SN', 'SN');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Serbia', 'RS', 'RS');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Seychelles', 'SC', 'SC');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Sierra Leone', 'SL', 'SL');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Singapore', 'SG', 'SG');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Slovakia', 'SK', 'SK');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Slovenia', 'SI', 'SI');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Solomon Islands', 'SB', 'SB');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Somalia', 'SO', 'SO');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('South Africa', 'ZA', 'ZA');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Spain', 'ES', 'ES');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Sri Lanka', 'LK', 'LK');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Sudan', 'SD', 'SD');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Suriname', 'SR', 'SR');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Swaziland', 'SZ', 'SZ');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Sweden', 'SE', 'SE');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Switzerland', 'CH', 'CH');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Syria', 'SY', 'SY');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Tajikistan', 'TJ', 'TJ');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Tanzania', 'TZ', 'TZ');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Thailand', 'TH', 'TH');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Timor-Leste (East Timor)', 'TL', 'TL');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Togo', 'TG', 'TG');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Tonga', 'TO', 'TO');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Trinidad and Tobago', 'TT', 'TT');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Tunisia', 'TN', 'TN');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Turkey', 'TR', 'TR');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Turkmenistan', 'TM', 'TM');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Tuvalu', 'TV', 'TV');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Uganda', 'UG', 'UG');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Ukraine', 'UA', 'UA');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('United Arab Emirates', 'AE', 'AE');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('United Kingdom', 'GB', 'GB');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Uruguay', 'UY', 'UY');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Uzbekistan', 'UZ', 'UZ');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Vanuatu', 'VU', 'VU');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Vatican City', 'VA', 'VA');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Venezuela', 'VE', 'VE');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Vietnam', 'VN', 'VN');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Yemen', 'YE', 'YE');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Zambia', 'ZM', 'ZM');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Zimbabwe', 'ZW', 'ZW');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Abkhazia', 'GE', 'GE');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Taiwan', 'TW', 'TW');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Nagorno-Karabakh', 'AZ', 'AZ');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Northern Cyprus', 'CY', 'CY');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Pridnestrovie (Transnistria)', 'MD', 'MD');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Somaliland', 'SO', 'SO');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('South Ossetia', 'GE', 'GE');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Ashmore and Cartier Islands', 'AU', 'AU');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Christmas Island', 'CX', 'CX');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Cocos (Keeling) Islands', 'CC', 'CC');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Coral Sea Islands', 'AU', 'AU');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Heard Island and McDonald Islands', 'HM', 'HM');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Norfolk Island', 'NF', 'NF');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('New Caledonia', 'NC', 'NC');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('French Polynesia', 'PF', 'PF');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Mayotte', 'YT', 'YT');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Saint Barthelemy', 'GP', 'GP');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Saint Martin', 'GP', 'GP');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Saint Pierre and Miquelon', 'PM', 'PM');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Wallis and Futuna', 'WF', 'WF');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('French Southern and Antarctic Lands', 'TF', 'TF');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Clipperton Island', 'PF', 'PF');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Bouvet Island', 'BV', 'BV');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Cook Islands', 'CK', 'CK');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Niue', 'NU', 'NU');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Tokelau', 'TK', 'TK');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Guernsey', 'GG', 'GG');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Isle of Man', 'IM', 'IM');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Jersey', 'JE', 'JE');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Anguilla', 'AI', 'AI');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Bermuda', 'BM', 'BM');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('British Indian Ocean Territory', 'IO', 'IO');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('British Virgin Islands', 'VG', 'VG');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Cayman Islands', 'KY', 'KY');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Falkland Islands (Islas Malvinas)', 'FK', 'FK');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Gibraltar', 'GI', 'GI');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Montserrat', 'MS', 'MS');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Pitcairn Islands', 'PN', 'PN');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Saint Helena', 'SH', 'SH');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('South Georgia & South Sandwich Islands', 'GS', 'GS');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Turks and Caicos Islands', 'TC', 'TC');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Northern Mariana Islands', 'MP', 'MP');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Puerto Rico', 'PR', 'PR');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('American Samoa', 'AS', 'AS');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Baker Island', 'UM', 'UM');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Guam', 'GU', 'GU');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Howland Island', 'UM', 'UM');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Jarvis Island', 'UM', 'UM');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Johnston Atoll', 'UM', 'UM');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Kingman Reef', 'UM', 'UM');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Midway Islands', 'UM', 'UM');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Navassa Island', 'UM', 'UM');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Palmyra Atoll', 'UM', 'UM');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('U.S. Virgin Islands', 'VI', 'VI');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Wake Island', 'UM', 'UM');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Hong Kong', 'HK', 'HK');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Macau', 'MO', 'MO');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Faroe Islands', 'FO', 'FO');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Greenland', 'GL', 'GL');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('French Guiana', 'GF', 'GF');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Guadeloupe', 'GP', 'GP');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Martinique', 'MQ', 'MQ');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Reunion', 'RE', 'RE');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Aland', 'AX', 'AX');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Aruba', 'AW', 'AW');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Netherlands Antilles', 'AN', 'AN');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Svalbard', 'SJ', 'SJ');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Ascension', 'AC', 'AC');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Tristan da Cunha', 'TA', 'TA');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Australian Antarctic Territory', 'AQ', 'AQ');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Ross Dependency', 'AQ', 'AQ');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Peter I Island', 'AQ', 'AQ');
INSERT INTO countries (country_name,country_code,country_name_short) VALUES ('Queen Maud Land', 'AQ', 'AQ');