TRUNCATE TABLE states;
INSERT INTO states (state_name,state_code,country_id) VALUES ('Alabama', 'AL', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Alaska', 'AK', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Arizona', 'AZ', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Arkansas', 'AR', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('California', 'CA', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Colorado', 'CO', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Connecticut', 'CT', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Delaware', 'DE', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Florida', 'FL', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Georgia', 'GA', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Hawaii', 'HI', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Idaho', 'ID', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Illinois', 'IL', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Indiana', 'IN', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Iowa', 'IA', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Kansas', 'KS', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Kentucky', 'KY', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Louisiana', 'LA', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Maine', 'ME', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Maryland', 'MD', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Massachusetts', 'MA', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Michigan', 'MI', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Minnesota', 'MN', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Mississippi', 'MS', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Missouri', 'MO', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Montana', 'MT', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Nebraska', 'NE', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Nevada', 'NV', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('New Hampshire', 'NH', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('New Jersey', 'NJ', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('New Mexico', 'NM', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('New York', 'NY', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('North Carolina', 'NC', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('North Dakota', 'ND', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Ohio', 'OH', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Oklahoma', 'OK', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Oregon', 'OR', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Pennsylvania', 'PA', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Rhode Island', 'RI', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('South Carolina', 'SC', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('South Dakota', 'SD', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Tennessee', 'TN', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Texas', 'TX', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Utah', 'UT', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Vermont', 'VT', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Virginia', 'VA', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Washington', 'WA', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('West Virginia', 'WV', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Wisconsin', 'WI', 1);
INSERT INTO states (state_name,state_code,country_id) VALUES ('Wyoming', 'WY', 1);