/**
 * Accounting Segment Permission model.
 *
 * Auto-generated by modelGenerator.
 *
 * @author Nicolas Iglesias <nicolas@clevertech.biz>
 */
module.exports = function(seq, dataTypes) {
	return seq.define("accounting_segment_permission", {
		"id" : {
			type : dataTypes.INTEGER, allowNull : false, primaryKey : true, autoIncrement : true
		},
		"is_shown" : {
			type : dataTypes.BOOLEAN, allowNull : true
		},
		"account_id" : {
			type : dataTypes.INTEGER, allowNull : true
		},
		"accounting_segment_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
		"department_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
	},{
		instanceMethods : {
		// place your custom model methods below.
		}
	});
}