/**
 * Account model.
 *
 * Auto-generated by modelGenerator.
 *
 * @author Nicolas Iglesias <nicolas@clevertech.biz>
 */
module.exports = function(seq, dataTypes) {
	return seq.define("account", {
		"id" : {
			type : dataTypes.INTEGER, allowNull : false, primaryKey : true, autoIncrement : true
		},
		"account_code" : {
			type : dataTypes.STRING, allowNull : true, max : 150
		},
		"segment_id" : {
			type : dataTypes.INTEGER, allowNull : true
		},
		"account_title" : {
			type : dataTypes.STRING, allowNull : true, max : 500
		},
		"account_short_title" : {
			type : dataTypes.STRING, allowNull : true, max : 200
		},
		"account_status" : {
			type : dataTypes.BOOLEAN, allowNull : true
		},
		"account_type" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"account_auth_limit" : {
			type : dataTypes.FLOAT, allowNull : true, max : 1179650
		},
		"alias" : {
			type : dataTypes.STRING, allowNull : true, max : 200
		},
		"cbsaname" : {
			type : dataTypes.STRING, allowNull : true, max : 200
		},
		"is_visible" : {
			type : dataTypes.BOOLEAN, allowNull : true
		},
		"created_date" : {
			type : dataTypes.DATE, allowNull : true
		},
		"created_by_id" : {
			type : dataTypes.INTEGER, allowNull : true
		},
		"modified_date" : {
			type : dataTypes.DATE, allowNull : true
		},
		"modified_by_id" : {
			type : dataTypes.INTEGER, allowNull : true
		},
		"segment04" : {
			type : dataTypes.STRING, allowNull : true, max : 100
		},
		"account04" : {
			type : dataTypes.STRING, allowNull : true, max : 100
		},
		"segment01" : {
			type : dataTypes.STRING, allowNull : true, max : 100
		},
		"account01" : {
			type : dataTypes.STRING, allowNull : true, max : 100
		},
		"segment00" : {
			type : dataTypes.STRING, allowNull : true, max : 100
		},
		"account00" : {
			type : dataTypes.STRING, allowNull : true, max : 100
		},
		"segment02" : {
			type : dataTypes.STRING, allowNull : true, max : 100
		},
		"account02" : {
			type : dataTypes.STRING, allowNull : true, max : 100
		},
		"segment05" : {
			type : dataTypes.STRING, allowNull : true, max : 100
		},
		"account05" : {
			type : dataTypes.STRING, allowNull : true, max : 100
		},
		"segment03" : {
			type : dataTypes.STRING, allowNull : true, max : 100
		},
		"account03" : {
			type : dataTypes.STRING, allowNull : true, max : 100
		},
		"segment06" : {
			type : dataTypes.STRING, allowNull : true, max : 100
		},
		"account06" : {
			type : dataTypes.STRING, allowNull : true, max : 100
		},
		"accounting_segment_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
		"client_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
	});
}