/**
 * Accounting System Type model.
 *
 * Auto-generated by modelGenerator.
 *
 * @author Nicolas Iglesias <nicolas@clevertech.biz>
 */
module.exports = function(seq, dataTypes) {
	return seq.define("accounting_system_type", {
		"id" : {
			type : dataTypes.INTEGER, allowNull : false, primaryKey : true, autoIncrement : true
		},
		"accounting_system_type_name" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"display_order" : {
			type : dataTypes.INTEGER, allowNull : true
		},
	},{
		instanceMethods : {
		// place your custom model methods below.
		}
	});
}