/**
 * Account model.
 *
 * Auto-generated by modelGenerator.
 *
 * @author Nicolas Iglesias <nico@webpolis.com.ar>
 */
var inflector = require('inflector');

exports.model = {
	// access your variables by adding the $$ prefix
	name : 'account',
	// map your database columns here
	fields : [
		{name : 'id', label : 'id'.humanize(), type : 'integer', required : true, primaryKey : true},
		{name : 'account_code', label : 'account_code'.humanize(), type : 'string', required : false, max : 150},
		{name : 'segment_id', label : 'segment_id'.humanize(), type : 'integer', required : false},
		{name : 'account_title', label : 'account_title'.humanize(), type : 'string', required : false, max : 500},
		{name : 'account_short_title', label : 'account_short_title'.humanize(), type : 'string', required : false, max : 200},
		{name : 'account_status', label : 'account_status'.humanize(), type : 'boolean', required : false},
		{name : 'account_type', label : 'account_type'.humanize(), type : 'string', required : false, max : 50},
		{name : 'account_auth_limit', label : 'account_auth_limit'.humanize(), type : 'float', required : false, max : 1179650},
		{name : 'alias', label : 'alias'.humanize(), type : 'string', required : false, max : 200},
		{name : 'cbsaname', label : 'cbsaname'.humanize(), type : 'string', required : false, max : 200},
		{name : 'is_visible', label : 'is_visible'.humanize(), type : 'boolean', required : false},
		{name : 'created_date', label : 'created_date'.humanize(), type : 'date', required : false},
		{name : 'created_by_id', label : 'created_by_id'.humanize(), type : 'integer', required : false},
		{name : 'modified_date', label : 'modified_date'.humanize(), type : 'date', required : false},
		{name : 'modified_by_id', label : 'modified_by_id'.humanize(), type : 'integer', required : false},
		{name : 'segment04', label : 'segment04'.humanize(), type : 'string', required : false, max : 100},
		{name : 'account04', label : 'account04'.humanize(), type : 'string', required : false, max : 100},
		{name : 'segment01', label : 'segment01'.humanize(), type : 'string', required : false, max : 100},
		{name : 'account01', label : 'account01'.humanize(), type : 'string', required : false, max : 100},
		{name : 'segment00', label : 'segment00'.humanize(), type : 'string', required : false, max : 100},
		{name : 'account00', label : 'account00'.humanize(), type : 'string', required : false, max : 100},
		{name : 'segment02', label : 'segment02'.humanize(), type : 'string', required : false, max : 100},
		{name : 'account02', label : 'account02'.humanize(), type : 'string', required : false, max : 100},
		{name : 'segment05', label : 'segment05'.humanize(), type : 'string', required : false, max : 100},
		{name : 'account05', label : 'account05'.humanize(), type : 'string', required : false, max : 100},
		{name : 'segment03', label : 'segment03'.humanize(), type : 'string', required : false, max : 100},
		{name : 'account03', label : 'account03'.humanize(), type : 'string', required : false, max : 100},
		{name : 'segment06', label : 'segment06'.humanize(), type : 'string', required : false, max : 100},
		{name : 'account06', label : 'account06'.humanize(), type : 'string', required : false, max : 100},
		{name : 'accounting_segment_id', label : 'accounting_segment_id'.humanize(), type : 'integer', required : true},
		{name : 'client_id', label : 'client_id'.humanize(), type : 'integer', required : true},
	],
	// place your custom model methods below.
	methods : {
		$instanceMethod : function(){ console.log('Prefix your instance methods\' name with a dollar sign ($). Example: model.$instanceMethod()');},
		classMethod : function(){ console.log('This class method is accesed statically. Example: this.models.modelName.classMethod()');}
	},
	relations : {
		hasOne:[],
		hasMany:[],
		belongsTo:[],
	}
}