/**
 * Accounting System File model.
 *
 * Auto-generated by modelGenerator.
 *
 * @author Nicolas Iglesias <nicolas@clevertech.biz>
 */
module.exports = function(seq, dataTypes) {
	return seq.define("accounting_system_file", {
		"id" : {
			type : dataTypes.INTEGER, allowNull : false, primaryKey : true, autoIncrement : true
		},
		"accounting_system_session_id" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"accounting_system_file" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"export_date" : {
			type : dataTypes.DATE, allowNull : true
		},
		"create_date" : {
			type : dataTypes.DATE, allowNull : false
		},
		"client_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
	});
}