/**
 * Accounting Segment model.
 *
 * Auto-generated by modelGenerator.
 *
 * @author Nicolas Iglesias <nicolas@clevertech.biz>
 */
module.exports = function(seq, dataTypes) {
	return seq.define("accounting_segment", {
		"id" : {
			type : dataTypes.INTEGER, allowNull : false, primaryKey : true, autoIncrement : true
		},
		"segment_title" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"description" : {
			type : dataTypes.STRING, allowNull : true, max : 500
		},
		"segment_auth_limit" : {
			type : dataTypes.FLOAT, allowNull : true, max : 1179650
		},
		"accounting_system_id" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"is_visible" : {
			type : dataTypes.BOOLEAN, allowNull : true
		},
		"display_order" : {
			type : dataTypes.INTEGER, allowNull : true
		},
		"created_date" : {
			type : dataTypes.DATE, allowNull : true
		},
		"created_by_id" : {
			type : dataTypes.INTEGER, allowNull : true
		},
		"modified_date" : {
			type : dataTypes.DATE, allowNull : true
		},
		"modified_by_id" : {
			type : dataTypes.INTEGER, allowNull : true
		},
		"client_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
	},{
		instanceMethods : {
		// place your custom model methods below.
		}
	});
}