/**
 * Acm Group Task model.
 *
 * Auto-generated by modelGenerator.
 *
 * @author Nicolas Iglesias <nicolas@clevertech.biz>
 */
module.exports = function(seq, dataTypes) {
	return seq.define("acm_group_task", {
		"id" : {
			type : dataTypes.INTEGER, allowNull : false, primaryKey : true, autoIncrement : true
		},
		"acm_groups_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
		"acm_tasks_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
	});
}