/**
 * Admin model.
 *
 * Auto-generated by modelGenerator.
 *
 * @author Nicolas Iglesias <nicolas@clevertech.biz>
 */
module.exports = function(seq, dataTypes) {
	return seq.define("admin", {
		"id" : {
			type : dataTypes.INTEGER, allowNull : false, primaryKey : true, autoIncrement : true
		},
		"name" : {
			type : dataTypes.STRING, allowNull : true, max : 100
		},
		"username" : {
			type : dataTypes.STRING, allowNull : true, max : 100
		},
		"password" : {
			type : dataTypes.STRING, allowNull : true, max : 100
		},
	});
}