/**
 * Client Bank model.
 *
 * Auto-generated by modelGenerator.
 *
 * @author Nicolas Iglesias <nicolas@clevertech.biz>
 */
module.exports = function(seq, dataTypes) {
	return seq.define("client_bank", {
		"id" : {
			type : dataTypes.INTEGER, allowNull : false, primaryKey : true, autoIncrement : true
		},
		"bank_name" : {
			type : dataTypes.STRING, allowNull : true, max : 250
		},
		"default_bank_id" : {
			type : dataTypes.INTEGER, allowNull : true
		},
		"description" : {
			type : dataTypes.STRING, allowNull : true, max : 1000
		},
		"connection_type" : {
			type : dataTypes.STRING, allowNull : true, max : 100
		},
		"web_address" : {
			type : dataTypes.STRING, allowNull : true, max : 250
		},
		"username" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"password" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"security_word" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"apikey" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"created_date" : {
			type : dataTypes.DATE, allowNull : true
		},
		"created_by_id" : {
			type : dataTypes.INTEGER, allowNull : true
		},
		"modified_date" : {
			type : dataTypes.DATE, allowNull : true
		},
		"modified_by_id" : {
			type : dataTypes.INTEGER, allowNull : true
		},
		"is_visible" : {
			type : dataTypes.BOOLEAN, allowNull : true
		},
		"client_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
	});
}