/**
 * Client Rule model.
 *
 * Auto-generated by modelGenerator.
 *
 * @author Nicolas Iglesias <nicolas@clevertech.biz>
 */
module.exports = function(seq, dataTypes) {
	return seq.define("client_rule", {
		"id" : {
			type : dataTypes.INTEGER, allowNull : false, primaryKey : true, autoIncrement : true
		},
		"default_auth_limit" : {
			type : dataTypes.FLOAT, allowNull : true, max : 1179650
		},
		"is_active" : {
			type : dataTypes.BOOLEAN, allowNull : true
		},
		"priority" : {
			type : dataTypes.INTEGER, allowNull : true
		},
		"default_approvers" : {
			type : dataTypes.STRING, allowNull : true, max : 500
		},
		"client_approvers" : {
			type : dataTypes.STRING, allowNull : true, max : 500
		},
		"created_date" : {
			type : dataTypes.DATE, allowNull : true
		},
		"created_by_id" : {
			type : dataTypes.INTEGER, allowNull : true
		},
		"modified_date" : {
			type : dataTypes.DATE, allowNull : true
		},
		"modified_by_id" : {
			type : dataTypes.INTEGER, allowNull : true
		},
		"client_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
		"default_rule_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
	},{
		instanceMethods : {
		// place your custom model methods below.
		}
	});
}