/**
 * Country model.
 *
 * Auto-generated by modelGenerator.
 *
 * @author Nicolas Iglesias <nicolas@clevertech.biz>
 */
var inflector = require('inflector');

exports.model = {
	// access your variables by adding the $$ prefix
	name : 'country',
	// map your database columns here
	fields : [
		{name : 'id', label : 'id'.humanize(), type : 'integer', required : true, primaryKey : true},
		{name : 'country_code', label : 'country_code'.humanize(), type : 'string', required : false, max : 100},
		{name : 'country_name', label : 'country_name'.humanize(), type : 'string', required : false, max : 150},
		{name : 'country_name_short', label : 'country_name_short'.humanize(), type : 'string', required : false, max : 100},
		{name : 'display_order', label : 'display_order'.humanize(), type : 'integer', required : false},
		{name : 'is_visible', label : 'is_visible'.humanize(), type : 'boolean', required : false},
	],
	// place your custom model methods below.
	methods : {
	},
	relations : {
		hasOne:[],
		hasMany:[
                    {model:'state', foreignKey:'country_id'}
                ],
		belongsTo:[],
	}
}