/**
 * Default Rule model.
 *
 * Auto-generated by modelGenerator.
 *
 * @author Nicolas Iglesias <nicolas@clevertech.biz>
 */
module.exports = function(seq, dataTypes) {
	return seq.define("default_rule", {
		"id" : {
			type : dataTypes.INTEGER, allowNull : false, primaryKey : true, autoIncrement : true
		},
		"default_rule_type" : {
			type : dataTypes.STRING, allowNull : true, max : 150
		},
		"default_rule_name" : {
			type : dataTypes.STRING, allowNull : true, max : 500
		},
		"default_authorization_limit" : {
			type : dataTypes.FLOAT, allowNull : true, max : 1179650
		},
		"default_approvers" : {
			type : dataTypes.STRING, allowNull : true, max : 500
		},
		"comment" : {
			type : dataTypes.STRING, allowNull : true, max : 1000
		},
	});
}