/**
 * Department model.
 *
 * Auto-generated by modelGenerator.
 *
 * @author Nicolas Iglesias <nicolas@clevertech.biz>
 */
module.exports = function(seq, dataTypes) {
	return seq.define("department", {
		"id" : {
			type : dataTypes.INTEGER, allowNull : false, primaryKey : true, autoIncrement : true
		},
		"department_name" : {
			type : dataTypes.STRING, allowNull : false, max : 50
		},
		"dept_auth_limit" : {
			type : dataTypes.FLOAT, allowNull : true, max : 1179650
		},
		"is_auth_required" : {
			type : dataTypes.BOOLEAN, allowNull : true
		},
		"is_super_department" : {
			type : dataTypes.BOOLEAN, allowNull : true
		},
		"is_processing" : {
			type : dataTypes.BOOLEAN, allowNull : true
		},
		"client_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
	},{
		instanceMethods : {
		// place your custom model methods below.
		}
	});
}