/**
 * Department model.
 *
 * Auto-generated by modelGenerator.
 *
 * @author Nicolas Iglesias <nicolas@clevertech.biz>
 */
var inflector = require('inflector');

exports.model = {
	// access your variables by adding the $$ prefix
	name : 'department',
	// map your database columns here
	fields : [
		{name : 'id', label : 'id'.humanize(), type : 'integer', required : true, primaryKey : true},
		{name : 'department_name', label : 'department_name'.humanize(), type : 'string', required : true, max : 50},
		{name : 'dept_auth_limit', label : 'Authorization Limit', type : 'float', required : false, max : 1179650},
		{name : 'is_auth_required', label : 'Additional Authorization', type : 'boolean', required : false},
		{name : 'is_super_department', label : 'is_super_department'.humanize(), type : 'boolean', required : false},
		{name : 'is_processing', label : 'is_processing'.humanize(), type : 'boolean', required : false},
		{name : 'client_id', label : 'client_id'.humanize(), type : 'integer', required : true},
	],
	// place your custom model methods below.
        methods : {
            getListableColumns : function(){
                return ['id','department_name', 'dept_auth_limit','is_auth_required']
            }
        },
	relations : {
		hasOne:[],
		hasMany:[],
		belongsTo:[
                    {model:'client', alias:'client', foreignKey: 'client_id'},
                ],
	}
}