/**
 * Invoice Approver model.
 *
 * Auto-generated by modelGenerator.
 *
 * @author Nicolas Iglesias <nicolas@clevertech.biz>
 */
module.exports = function(seq, dataTypes) {
	return seq.define("invoice_approver", {
		"id" : {
			type : dataTypes.INTEGER, allowNull : false, primaryKey : true, autoIncrement : true
		},
		"approval_date" : {
			type : dataTypes.DATE, allowNull : true
		},
		"rejection_date" : {
			type : dataTypes.DATE, allowNull : true
		},
		"rejection_reason" : {
			type : dataTypes.STRING, allowNull : true, max : 500
		},
		"_approval_date" : {
			type : dataTypes.DATE, allowNull : true
		},
		"reject_date" : {
			type : dataTypes.DATE, allowNull : true
		},
		"invoice_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
		"invoice_line_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
		"client_rule_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
		"user_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
	},{
		instanceMethods : {
		// place your custom model methods below.
		}
	});
}