/**
 * Invoice Amount Bracket model.
 *
 * Auto-generated by modelGenerator.
 *
 * @author Nicolas Iglesias <nicolas@clevertech.biz>
 */
module.exports = function(seq, dataTypes) {
	return seq.define("invoice_amount_bracket", {
		"id" : {
			type : dataTypes.INTEGER, allowNull : false, primaryKey : true, autoIncrement : true
		},
		"invoice_amount" : {
			type : dataTypes.FLOAT, allowNull : true, max : 1179650
		},
		"client_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
	});
}