/**
 * Invoice model.
 *
 * Auto-generated by modelGenerator.
 *
 * @author Nicolas Iglesias <nicolas@clevertech.biz>
 */
module.exports = function(seq, dataTypes) {
	return seq.define("invoice", {
		"id" : {
			type : dataTypes.INTEGER, allowNull : false, primaryKey : true, autoIncrement : true
		},
		"invoice_number" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"created_date" : {
			type : dataTypes.DATE, allowNull : true
		},
		"invoice_date" : {
			type : dataTypes.DATE, allowNull : true
		},
		"receipt_file" : {
			type : dataTypes.STRING, allowNull : true, max : 512
		},
		"submitted_date" : {
			type : dataTypes.DATE, allowNull : true
		},
		"submitted_by_id" : {
			type : dataTypes.INTEGER, allowNull : true
		},
		"requested_by_id" : {
			type : dataTypes.INTEGER, allowNull : true
		},
		"required_date" : {
			type : dataTypes.DATE, allowNull : true
		},
		"acc_approved_date" : {
			type : dataTypes.DATE, allowNull : true
		},
		"acc_approved_by_id" : {
			type : dataTypes.INTEGER, allowNull : true
		},
		"approved_date" : {
			type : dataTypes.DATE, allowNull : true
		},
		"approved_by_id" : {
			type : dataTypes.INTEGER, allowNull : true
		},
		"exported_date" : {
			type : dataTypes.DATE, allowNull : true
		},
		"exported_by_id" : {
			type : dataTypes.INTEGER, allowNull : true
		},
		"rejected_date" : {
			type : dataTypes.DATE, allowNull : true
		},
		"rejected_by_id" : {
			type : dataTypes.INTEGER, allowNull : true
		},
		"rejected_reason" : {
			type : dataTypes.TEXT, allowNull : true
		},
		"rejected_invoice_id" : {
			type : dataTypes.INTEGER, allowNull : true
		},
		"project_name" : {
			type : dataTypes.STRING, allowNull : true, max : 150
		},
		"address" : {
			type : dataTypes.STRING, allowNull : true, max : 255
		},
		"address2" : {
			type : dataTypes.STRING, allowNull : true, max : 255
		},
		"city" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"state_id" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"zipcode" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"country_id" : {
			type : dataTypes.STRING, allowNull : true, max : 100
		},
		"bank_name" : {
			type : dataTypes.STRING, allowNull : true, max : 100
		},
		"bank_address" : {
			type : dataTypes.STRING, allowNull : true, max : 255
		},
		"bank_routing_number" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"bank_acct_number" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"is_wire_transfer" : {
			type : dataTypes.BOOLEAN, allowNull : true
		},
		"description" : {
			type : dataTypes.STRING, allowNull : true, max : 2000
		},
		"total_amount" : {
			type : dataTypes.FLOAT, allowNull : true, max : 1179650
		},
		"is_deleted" : {
			type : dataTypes.BOOLEAN, allowNull : true
		},
		"is_expense" : {
			type : dataTypes.BOOLEAN, allowNull : true
		},
		"is_saved" : {
			type : dataTypes.BOOLEAN, allowNull : true
		},
		"is_archived" : {
			type : dataTypes.BOOLEAN, allowNull : true
		},
		"is_billable" : {
			type : dataTypes.BOOLEAN, allowNull : true
		},
		"accounting_system_session_id" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"invoice_source" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"send_via" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"acc_approver" : {
			type : dataTypes.INTEGER, allowNull : true
		},
		"send_invoice" : {
			type : dataTypes.BOOLEAN, allowNull : true
		},
		"forward_approver" : {
			type : dataTypes.INTEGER, allowNull : true
		},
		"created_by_id" : {
			type : dataTypes.INTEGER, allowNull : true
		},
		"modified_date" : {
			type : dataTypes.DATE, allowNull : true
		},
		"modified_by_id" : {
			type : dataTypes.INTEGER, allowNull : true
		},
		"client_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
		"invoice_type_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
		"invoice_status_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
		"vendor_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
		"accounting_system_file_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
	});
}