/**
 * Invoice Line model.
 *
 * Auto-generated by modelGenerator.
 *
 * @author Nicolas Iglesias <nicolas@clevertech.biz>
 */
var inflector = require('inflector');

exports.model = {
	// access your variables by adding the $$ prefix
	name : 'invoice_line',
	// map your database columns here
	fields : [
		{name : 'id', label : 'id'.humanize(), type : 'integer', required : true, primaryKey : true},
		{name : 'amount', label : 'amount'.humanize(), type : 'float', required : false, max : 1179650},
		{name : 'line_date', label : 'line_date'.humanize(), type : 'date', required : false},
		{name : 'rejection_reason', label : 'rejection_reason'.humanize(), type : 'string', required : false, max : 2000},
		{name : 'rejected_by_id', label : 'rejected_by_id'.humanize(), type : 'integer', required : false},
		{name : 'rejected_date', label : 'rejected_date'.humanize(), type : 'date', required : false},
		{name : 'comment', label : 'comment'.humanize(), type : 'string', required : false, max : 500},
		{name : 'attached_file', label : 'attached_file'.humanize(), type : 'string', required : false, max : 255},
		{name : 'attached_zoom_file', label : 'attached_zoom_file'.humanize(), type : 'string', required : false, max : 255},
		{name : 'original_file', label : 'original_file'.humanize(), type : 'string', required : false, max : 255},
		{name : 'invoice_id', label : 'invoice_id'.humanize(), type : 'integer', required : true},
	],
	// place your custom model methods below.
	methods : {
		$instanceMethod : function(){ console.log('Prefix your instance methods\' name with a dollar sign ($). Example: model.$instanceMethod()');},
		classMethod : function(){ console.log('This class method is accesed statically. Example: this.$$.models.modelName.classMethod()');}
	},
	relations : {
		hasOne:[],
		hasMany:[],
		belongsTo:[],
	}
}