/**
 * Invoice Line model.
 *
 * Auto-generated by modelGenerator.
 *
 * @author Nicolas Iglesias <nicolas@clevertech.biz>
 */
module.exports = function(seq, dataTypes) {
	return seq.define("invoice_line", {
		"id" : {
			type : dataTypes.INTEGER, allowNull : false, primaryKey : true, autoIncrement : true
		},
		"amount" : {
			type : dataTypes.FLOAT, allowNull : true, max : 1179650
		},
		"line_date" : {
			type : dataTypes.DATE, allowNull : true
		},
		"rejection_reason" : {
			type : dataTypes.STRING, allowNull : true, max : 2000
		},
		"rejected_by_id" : {
			type : dataTypes.INTEGER, allowNull : true
		},
		"rejected_date" : {
			type : dataTypes.DATE, allowNull : true
		},
		"comment" : {
			type : dataTypes.STRING, allowNull : true, max : 500
		},
		"attached_file" : {
			type : dataTypes.STRING, allowNull : true, max : 255
		},
		"attached_zoom_file" : {
			type : dataTypes.STRING, allowNull : true, max : 255
		},
		"original_file" : {
			type : dataTypes.STRING, allowNull : true, max : 255
		},
		"invoice_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
	});
}