/**
 * Invoice File model.
 *
 * Auto-generated by modelGenerator.
 *
 * @author Nicolas Iglesias <nicolas@clevertech.biz>
 */
module.exports = function(seq, dataTypes) {
	return seq.define("invoice_file", {
		"id" : {
			type : dataTypes.INTEGER, allowNull : false, primaryKey : true, autoIncrement : true
		},
		"attached_file" : {
			type : dataTypes.STRING, allowNull : true, max : 500
		},
		"attached_zoom_file" : {
			type : dataTypes.STRING, allowNull : true, max : 500
		},
		"original_file" : {
			type : dataTypes.STRING, allowNull : true, max : 500
		},
		"created_by_id" : {
			type : dataTypes.INTEGER, allowNull : true
		},
		"created_date" : {
			type : dataTypes.DATE, allowNull : true
		},
		"invoice_line_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
	});
}