/**
 * Invoice Amount Bracket Approver model.
 *
 * Auto-generated by modelGenerator.
 *
 * @author Nicolas Iglesias <nicolas@clevertech.biz>
 */
module.exports = function(seq, dataTypes) {
	return seq.define("invoice_amount_bracket_approver", {
		"id" : {
			type : dataTypes.INTEGER, allowNull : false, primaryKey : true, autoIncrement : true
		},
		"client_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
		"user_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
		"invoice_amount_bracket_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
	},{
		instanceMethods : {
		// place your custom model methods below.
		}
	});
}