/**
 * Invoice File model.
 *
 * Auto-generated by modelGenerator.
 *
 * @author Nicolas Iglesias <nicolas@clevertech.biz>
 */
var inflector = require('inflector');

exports.model = {
	// access your variables by adding the $$ prefix
	name : 'invoice_file',
	// map your database columns here
	fields : [
		{name : 'id', label : 'id'.humanize(), type : 'integer', required : true, primaryKey : true},
		{name : 'attached_file', label : 'attached_file'.humanize(), type : 'string', required : false, max : 500},
		{name : 'attached_zoom_file', label : 'attached_zoom_file'.humanize(), type : 'string', required : false, max : 500},
		{name : 'original_file', label : 'original_file'.humanize(), type : 'string', required : false, max : 500},
		{name : 'created_by_id', label : 'created_by_id'.humanize(), type : 'integer', required : false},
		{name : 'created_date', label : 'created_date'.humanize(), type : 'date', required : false},
		{name : 'invoice_line_id', label : 'invoice_line_id'.humanize(), type : 'integer', required : true},
	],
	// place your custom model methods below.
	methods : {
		$instanceMethod : function(){ console.log('Prefix your instance methods\' name with a dollar sign ($). Example: model.$instanceMethod()');},
		classMethod : function(){ console.log('This class method is accesed statically. Example: this.$$.models.modelName.classMethod()');}
	},
	relations : {
		hasOne:[],
		hasMany:[],
		belongsTo:[],
	}
}