/**
 * Invoice Line Segment model.
 *
 * Auto-generated by modelGenerator.
 *
 * @author Nicolas Iglesias <nicolas@clevertech.biz>
 */
module.exports = function(seq, dataTypes) {
	return seq.define("invoice_line_segment", {
		"id" : {
			type : dataTypes.INTEGER, allowNull : false, primaryKey : true, autoIncrement : true
		},
		"amount" : {
			type : dataTypes.FLOAT, allowNull : true, max : 1179650
		},
		"comment" : {
			type : dataTypes.STRING, allowNull : true, max : 500
		},
		"segment01" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"segment02" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"segment03" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"segment04" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"segment05" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"segment06" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"segment07" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"segment08" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"segment09" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"segment10" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"segment11" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"segment12" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"segment13" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"segment14" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"segment15" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"account01" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"account02" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"segment00" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"account00" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"account03" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"account04" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"account05" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"invoice_line_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
	});
}