/**
 * Invoice Status model.
 *
 * Auto-generated by modelGenerator.
 *
 * @author Nicolas Iglesias <nicolas@clevertech.biz>
 */
module.exports = function(seq, dataTypes) {
	return seq.define("invoice_status", {
		"id" : {
			type : dataTypes.INTEGER, allowNull : false, primaryKey : true, autoIncrement : true
		},
		"invoice_status_name" : {
			type : dataTypes.STRING, allowNull : true, max : 100
		},
	});
}