/**
 * Permission model.
 *
 * Auto-generated by modelGenerator.
 *
 * @author Nicolas Iglesias <nicolas@clevertech.biz>
 */
module.exports = function(seq, dataTypes) {
	return seq.define("permission", {
		"id" : {
			type : dataTypes.INTEGER, allowNull : false, primaryKey : true, autoIncrement : true
		},
		"permission_name" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"description" : {
			type : dataTypes.STRING, allowNull : true, max : 250
		},
	},{
		instanceMethods : {
		// place your custom model methods below.
		}
	});
}