/**
 * Sysdiagram model.
 *
 * Auto-generated by modelGenerator.
 *
 * @author Nicolas Iglesias <nicolas@clevertech.biz>
 */
module.exports = function(seq, dataTypes) {
	return seq.define("sysdiagram", {
		"id" : {
			type : dataTypes.INTEGER, allowNull : false, primaryKey : true, autoIncrement : true
		},
		"name" : {
			type : dataTypes.STRING, allowNull : false, max : 160
		},
		"principal_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
		"version" : {
			type : dataTypes.INTEGER, allowNull : true
		},
		"definition" : {
			type : undefined, allowNull : true
		},
	});
}