/**
 * Template model.
 *
 * Auto-generated by modelGenerator.
 *
 * @author Nicolas Iglesias <nicolas@clevertech.biz>
 */
module.exports = function(seq, dataTypes) {
	return seq.define("template", {
		"id" : {
			type : dataTypes.INTEGER, allowNull : false, primaryKey : true, autoIncrement : true
		},
		"format" : {
			type : dataTypes.STRING, allowNull : true, max : 300
		},
		"template_name" : {
			type : dataTypes.STRING, allowNull : true, max : 300
		},
		"is_default" : {
			type : dataTypes.BOOLEAN, allowNull : false
		},
		"start" : {
			type : dataTypes.INTEGER, allowNull : false
		},
		"end" : {
			type : dataTypes.INTEGER, allowNull : false
		},
		"user_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
		"invoice_type_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
	},{
		instanceMethods : {
		// place your custom model methods below.
		}
	});
}