/**
 * Todo List model.
 *
 * Auto-generated by modelGenerator.
 *
 * @author Nicolas Iglesias <nicolas@clevertech.biz>
 */
module.exports = function(seq, dataTypes) {
	return seq.define("todo_list", {
		"id" : {
			type : dataTypes.INTEGER, allowNull : false, primaryKey : true, autoIncrement : true
		},
		"status_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
		"todo_list_title" : {
			type : dataTypes.STRING, allowNull : true, max : 255
		},
		"todo_list_desc" : {
			type : dataTypes.TEXT, allowNull : true
		},
		"created_by" : {
			type : dataTypes.INTEGER, allowNull : false
		},
		"create_date" : {
			type : dataTypes.DATE, allowNull : false
		},
		"is_deleted" : {
			type : dataTypes.BOOLEAN, allowNull : false
		},
		"client_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
	},{
		instanceMethods : {
		// place your custom model methods below.
		}
	});
}