/**
 * Track Change model.
 *
 * Auto-generated by modelGenerator.
 *
 * @author Nicolas Iglesias <nicolas@clevertech.biz>
 */
module.exports = function(seq, dataTypes) {
	return seq.define("track_change", {
		"id" : {
			type : dataTypes.INTEGER, allowNull : false, primaryKey : true, autoIncrement : true
		},
		"record_id" : {
			type : dataTypes.INTEGER, allowNull : true
		},
		"details" : {
			type : dataTypes.TEXT, allowNull : true
		},
		"created_date" : {
			type : dataTypes.DATE, allowNull : true
		},
		"user_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
		"record_type_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
	});
}