/**
 * User Credit Card model.
 *
 * Auto-generated by modelGenerator.
 *
 * @author Nicolas Iglesias <nicolas@clevertech.biz>
 */
module.exports = function(seq, dataTypes) {
	return seq.define("user_credit_card", {
		"id" : {
			type : dataTypes.INTEGER, allowNull : false, primaryKey : true, autoIncrement : true
		},
		"credit_card_number" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"user_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
		"client_bank_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
	},{
		instanceMethods : {
		// place your custom model methods below.
		}
	});
}