/**
 * Users Department model.
 *
 * Auto-generated by modelGenerator.
 *
 * @author Nicolas Iglesias <nicolas@clevertech.biz>
 */
module.exports = function(seq, dataTypes) {
	return seq.define("users_department", {
		"id" : {
			type : dataTypes.INTEGER, allowNull : false, primaryKey : true, autoIncrement : true
		},
		"departments_department_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
		"users_user_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
	});
}