/**
 * Vendor model.
 *
 * Auto-generated by modelGenerator.
 *
 * @author Nicolas Iglesias <nicolas@clevertech.biz>
 */
module.exports = function(seq, dataTypes) {
	return seq.define("vendor", {
		"id" : {
			type : dataTypes.INTEGER, allowNull : false, primaryKey : true, autoIncrement : true
		},
		"vendor_name" : {
			type : dataTypes.STRING, allowNull : true, max : 250
		},
		"address" : {
			type : dataTypes.STRING, allowNull : true, max : 250
		},
		"address2" : {
			type : dataTypes.STRING, allowNull : true, max : 250
		},
		"city" : {
			type : dataTypes.STRING, allowNull : true, max : 100
		},
		"zipcode" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"phone" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"fax" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"email" : {
			type : dataTypes.STRING, allowNull : true, max : 350
		},
		"first_name" : {
			type : dataTypes.STRING, allowNull : true, max : 150
		},
		"last_name" : {
			type : dataTypes.STRING, allowNull : true, max : 150
		},
		"title" : {
			type : dataTypes.STRING, allowNull : true, max : 150
		},
		"accounting_system_id" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"is_credit_card" : {
			type : dataTypes.BOOLEAN, allowNull : true
		},
		"is_visible" : {
			type : dataTypes.BOOLEAN, allowNull : true
		},
		"is_active" : {
			type : dataTypes.BOOLEAN, allowNull : true
		},
		"is_approved" : {
			type : dataTypes.BOOLEAN, allowNull : true
		},
		"is_deleted" : {
			type : dataTypes.INTEGER, allowNull : true
		},
		"created_date" : {
			type : dataTypes.DATE, allowNull : true
		},
		"created_by_id" : {
			type : dataTypes.INTEGER, allowNull : true
		},
		"modified_date" : {
			type : dataTypes.DATE, allowNull : true
		},
		"modified_by_id" : {
			type : dataTypes.INTEGER, allowNull : true
		},
		"approved_to_import_date" : {
			type : dataTypes.DATE, allowNull : true
		},
		"vendor_type_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
		"state_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
		"country_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
		"client_id" : {
			type : dataTypes.INTEGER, allowNull : false
		},
	});
}