/**
 * Vendor Type model.
 *
 * Auto-generated by modelGenerator.
 *
 * @author Nicolas Iglesias <nicolas@clevertech.biz>
 */
module.exports = function(seq, dataTypes) {
	return seq.define("vendor_type", {
		"id" : {
			type : dataTypes.INTEGER, allowNull : false, primaryKey : true, autoIncrement : true
		},
		"vendor_type_name" : {
			type : dataTypes.STRING, allowNull : true, max : 50
		},
		"is_company" : {
			type : dataTypes.BOOLEAN, allowNull : true
		},
	},{
		instanceMethods : {
		// place your custom model methods below.
		}
	});
}