/**
 * Vendor model.
 *
 * Auto-generated by modelGenerator.
 *
 * @author Nicolas Iglesias <nicolas@clevertech.biz>
 */
var inflector = require('inflector');

exports.model = {
	// access your variables by adding the $$ prefix
	name : 'vendor',
	// map your database columns here
	fields : [
		{name : 'id', label : 'id'.humanize(), type : 'integer', required : true, primaryKey : true},
		{name : 'vendor_name', label : 'vendor_name'.humanize(), type : 'string', required : false, max : 250},
		{name : 'address', label : 'address'.humanize(), type : 'string', required : false, max : 250},
		{name : 'address2', label : 'address2'.humanize(), type : 'string', required : false, max : 250},
		{name : 'city', label : 'city'.humanize(), type : 'string', required : false, max : 100},
		{name : 'zipcode', label : 'zipcode'.humanize(), type : 'string', required : false, max : 50},
		{name : 'phone', label : 'phone'.humanize(), type : 'string', required : false, max : 50},
		{name : 'fax', label : 'fax'.humanize(), type : 'string', required : false, max : 50},
		{name : 'email', label : 'email'.humanize(), type : 'string', required : false, max : 350},
		{name : 'first_name', label : 'first_name'.humanize(), type : 'string', required : false, max : 150},
		{name : 'last_name', label : 'last_name'.humanize(), type : 'string', required : false, max : 150},
		{name : 'title', label : 'title'.humanize(), type : 'string', required : false, max : 150},
		{name : 'accounting_system_id', label : 'Accounting Code', type : 'string', required : false, max : 50},
		{name : 'is_credit_card', label : 'is_credit_card'.humanize(), type : 'boolean', required : false},
		{name : 'is_visible', label : 'is_visible'.humanize(), type : 'boolean', required : false},
		{name : 'is_active', label : 'is_active'.humanize(), type : 'boolean', required : false},
		{name : 'is_approved', label : 'is_approved'.humanize(), type : 'boolean', required : false},
		{name : 'is_deleted', label : 'is_deleted'.humanize(), type : 'integer', required : false},
		{name : 'created_date', label : 'created_date'.humanize(), type : 'date', required : false},
		{name : 'created_by_id', label : 'created_by_id'.humanize(), type : 'integer', required : false},
		{name : 'modified_date', label : 'modified_date'.humanize(), type : 'date', required : false},
		{name : 'modified_by_id', label : 'modified_by_id'.humanize(), type : 'integer', required : false},
		{name : 'approved_to_import_date', label : 'approved_to_import_date'.humanize(), type : 'date', required : false},
		{name : 'vendor_type_id', label : 'vendor_type_id'.humanize(), type : 'integer', required : true},
		{name : 'state_id', label : 'State', type : 'integer', required : true},
		{name : 'country_id', label : 'country_id'.humanize(), type : 'integer', required : true},
		{name : 'client_id', label : 'client_id'.humanize(), type : 'integer', required : true},
	],
	// place your custom model methods below.
        methods : {
            getListableColumns : function(){
                return ['id','vendor_name', 'email','accounting_system_id','state_id']
            }
        },
	relations : {
		hasOne:[],
		hasMany:[],
		belongsTo:[],
	}
}